### PR TITLE
Domain links now possible

### PR DESCRIPTION
**Pull request by FlTr**
…s first character.

```
[FOO](!/bar)
```

### CODE REVIEW

**Comment by markseu** [comment]
I would like to merge, but GitHub shows me five changed files. Not sure why, it should be one?

**Comment by FlTr** [comment]
4 of them should be updates coming from master

**Comment by markseu** [comment]
I think the binary file should be deleted.

**Comment by markseu** [comment]
Great, thank you

**Comment by FlTr** [comment]
Great Support. Great CMS

**Pull request merged**
