### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

*Total: 65.87kb -> 61.26kb (7%)

\system\themes\assets\icon.png -- 2.31kb -> 1.21kb (47.48%)
\media\images\picture.jpg -- 61.46kb -> 58.12kb (5.44%)
\media\thumbnails\picture-100x40.jpg -- 2.10kb -> 1.93kb (8.41%)

### CODE REVIEW

**Comment by markseu** [comment]
Hi, looks like color of JPG files have changed. Want to send me a pull request for PNG only?

**Comment by dabutvin** [comment]
I am following up with Magick.NET project on possible reasons for this happening. Replaced with https://github.com/datenstrom/yellow/pull/291

**Comment by dlemstra** [comment]
@markseu Can I use your `picture.jpg` file in a unit test for a fix in the software used by @dabutvin?

**Comment by markseu** [comment]
@dlemstra Sure, good luck with your test

**Pull request closed without merging**
